language: c
before_script:
  - cmake --version

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - gcc-avr
      - binutils-avr
      - avr-libc
      
script:
  - mkdir cibuild
  - cd cibuild
  - cmake -DBOARD=MEGA -DCMAKE_TOOLCHAIN_FILE=`pwd`/../demo/toolchain.cmake ../demo && make -j VERBOSE=1
  - make
  - avr-size main.elf