language: c
before_script:
  - cmake --version

env:
  - CC=avr-gcc
  
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - gcc-avr
      - binutils-avr
      - avr-libc
      
script:
  - mkdir cibuild
  - cd cibuild
  - avr-gcc --version
  - CC=avr-gcc; cmake -DBOARD=MEGA -DCMAKE_TOOLCHAIN_FILE=`pwd`/../demo/toolchain.cmake ../demo
  - make -j VERBOSE=1
  - avr-size main.elf